### ISSUE TITLE
Hosting at BASE URI

### ISSUE THREAD

**Issue by 3sv** [HajoRijgersberg/OM#1]
In the README the Base URI proposed is "http://www.ontology-of-units-of-measure.org/resource/om-2/".

That URL can for the moment not be de-referrenced, the ontology is not served at that domain/path. Are there any plans to do so in the future, or should an alternate URL be used?

It is valuable to be able to refer to the om namespace from external files with a given URL, where applications can then fetch the actual ontology of units of measure when needed.

Best regards,
Dries

**Comment by jmkeil** [comment]
[WIDOCO](https://github.com/dgarijo/Widoco) might be a good point to start. It is not perfect for ABox rich ontologies like OM, but it requires just a simple web space and little time to provide full dereferencing and content negotiation.

**Comment by HajoRijgersberg** [comment]
Dear people,
My apologies - I wasn't aware of these messages. I'll discuss the issue within our team. I'll come back to this sooner! :)
Best, Hajo

**Comment by HajoRijgersberg** [comment]
No DNS entry was yet requested for the uri http://www.ontology-of-units-of-measure.org/resource/om-2, which in the mean time has been done.
Does this tackle the issue for you sufficiently?
In the future, OM will have its own web portal: OMVoc. Looking forward to this; I'll keep you up to date.

**Comment by lapsedPacifist** [comment]
I think this should be closed?

**Comment by HajoRijgersberg** [comment]
Yes, I think so. Thanx!

**Comment by HajoRijgersberg** [comment]
Issue tackled. Remaining issue in 'Make LOV entry'.
