### ISSUE TITLE
Stability & readiness for use-cases?

### ISSUE THREAD

**Issue by pospi** [HajoRijgersberg/OM#21]
Hi there! :)

Just a question- I can see that this work is somewhat under active development, but am curious from the authors' perspective whether it has stabilised enough for integration into a production system. Also curious whether automatic unit conversion is an explicit goal for the project, and how one might go about plugging a reasoner in to perform that task (apologies for the basic question, I'm a novice with those kinds of systems).

More context at https://github.com/valueflows/valueflows/issues/268#issuecomment-532510494

**Comment by pospi** [comment]
I think @samrose answered this best in https://github.com/valueflows/valueflows/issues/268#issuecomment-534585173 - closing but feel free to add any additional context and information as you feel necessary (:

**Comment by HajoRijgersberg** [comment]
Hi Pospi,
Sorry for my late reply!! And thanks for your message! :)
This might also be of interest to you: https://github.com/dieudonne-willems/om-java-libs. Java software accompanying OM.
Looking forward to hearing from you what you think of it!
Best, Hajo
