### ISSUE TITLE
Additional unit for om:Frequency

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [HajoRijgersberg/OM#3]
Dear Hajo, dear OM developers,

first of all my appreciation for developing OM ontology which I find a wonderful ontology to capture units and quantities in the semantic web.

Today I discovered there might be some additional unit for om:Frequency added: 'reciprocalMinute'

I have been motivated for this as I have been looking for a way to express the unit of a signal as revolutions per minute (rpm) frequently appearing in engineering (e.g. cars).

It would be great if a respective unit is added similar to the existing om:reciprocalDay and om:reciprocalHour.

Thanks

Georg

**Comment by HajoRijgersberg** [comment]
Hi Georg,

Thanks for your kind words and compliments! Sorry for my late reply; apparently I don't receive messages in my emailbox that someone has sent me a message in GitHub. So I'll check more often.
ReciprocalMinute seems to me like an important unit to add. I aim to do that within a week. Would that be convenient for you?
I'll keep you up to date! Thanks for this suggestion!

Best, Hajo

**Comment by HajoRijgersberg** [comment]
Processed the above issue. Just uploaded a new version of OM.

**Comment by GeorgFerdinandSchneider** [comment]
Hi Hajo,

thanks for taking this comment up and I am happy that the novel unit is introduced.

I think we can close this issue then.

closed()

**Comment by HajoRijgersberg** [comment]
You're welcome; thanks!
