### ISSUE TITLE
Request to Register/Submit OM to LOV

### ISSUE THREAD

**Issue by conceptminers1** [HajoRijgersberg/OM#36]
While doing a literature study on Ontologies I came across OM. It's really great, multi-purpose and extremely useful. 

May I request you to kindly Submit at [LOV Suggest](https://lov.linkeddata.es/dataset/lov/suggest)

Many Thanks

**Comment by HajoRijgersberg** [comment]
Hi,

Thanks for your hint! :)
Hopefully you can help me. I've dived into LOV before, but it appeared it wasn't clear whether the namespace abbreviation 'om' of OM should be changed. I've indicated that I can't do that, that I'm afraid of any (unforeseen) consequences, apart from that it has to do with identity of OM.
Please see: https://github.com/HajoRijgersberg/OM/issues/10
Can you perhaps help me out on this?
Thank you so much in advance!

Best, Hajo

**Comment by conceptminers1** [comment]
Thanks Hajo, I shall try.

**Comment by conceptminers1** [comment]
Hi Hajo

RDF Validator Shows Load Error
RDF Load Error
An attempt to load the RDF from URI 'http://ontology-of-units-of-measure.org/resource/om-2/' failed. (Cannot open stream.)

Also it doesn't load in WebVOWL.

**Comment by HajoRijgersberg** [comment]
Thanks! 👍 
I have to dive into this.
The ontology is in the file om-2.0.rdf:
https://github.com/HajoRijgersberg/OM/blob/master/om-2.0.rdf
Hope this helps?

Best, Hajo

**Comment by conceptminers1** [comment]
Thanks Hajo, This link works perfect...
I could parse it.

**Comment by HajoRijgersberg** [comment]
Hi,
Thank you so much! :)
The prefix is the namespace, I guess?
Yes, you can submit to LOV, I would very much appreciate that!
The prefix should be om, for reasons mentioned above.
Thank you so much once again! Please keep me up to date! :)

**Comment by conceptminers1** [comment]
Surely, Hajo. Many Thanks. Have A Great Day !

**Comment by HajoRijgersberg** [comment]
Thanks, you too! :)

**Comment by conceptminers1** [comment]
Hi Hajo, 
Extremely happy to inform that LOV team has included OM ontology to LOV. The namespace prefix assigned is "oum".

https://lov.linkeddata.es/dataset/lov/vocabs/oum

Wishing Best,

**Comment by conceptminers1** [comment]
Pl ref our story...On Medium
Pl advise necessary changes or 
If anybody from your team likes to publish I can always delete the story.
“Units of Measurement of Ontology Added to LOV” https://link.medium.com/fVXqSdNNo8

**Comment by HajoRijgersberg** [comment]
Hi,
Thank you so much!! :) This is a great step for OM!
What does your last message mean (e.g., the PI's)?
All the best to you too! Hajo

**Comment by conceptminers1** [comment]
Many Thanks Hajo, 
Its really great work you have input to bring this ontology to world. I feel lucky and honoured to be in contact with you and submit on your behalf. 
I am excited so I shared an update at Medium

**Comment by HajoRijgersberg** [comment]
Hi Bhoomin,

Thank you so much for your kind words and your effort! I feel honoured that you did this for me, and also for people who will find and use OM through LOV. :)
And also thanks for the nice message that you wrote about OM and your submission to LOV! :)

All the best, Hajo

**Comment by conceptminers1** [comment]
Many Thanks Hajo, Wishing Best to You and the Team.

**Comment by conceptminers1** [comment]
Didn't realize the issue was resolved ! Sorry for delay.

**Comment by HajoRijgersberg** [comment]
No problem! Thanx! :)

**Comment by conceptminers1** [comment]
Hi Hajo,

In fact, I must thank you. It's so nice of you to be welcoming and trusting.

You are a great contributor to the field of Ontology.

I think, if you wish, you could contribute or present your work in the ekgf.org. However, I leave it to your choice.

Pl let me know if you feel I could be of any help.

Wishing Best of Safety and Great Health ...

Bhoomin Pandya.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HajoRijgersberg** [comment]
Hi Bhoomin.

Thanks for your kind words! :)  All the same!
Ah, I see the ekgf.org has already passed. Not sure if I could have attended, but I appear to be to late anyway..
I'll definitely let you know if you can help, thanx! :)

All the best to you too!
Hajo

**Comment by conceptminers1** [comment]
Hi Hajo,

Many Thanks.

I shall inform you in advance, if I feel you can participate.

Best Regards,
Bhoomin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
