### ISSUE TITLE
The Logo of OM

### ISSUE THREAD

**Issue by cmplstofB** [HajoRijgersberg/OM#38]
This issue may be trivial, sorry but I am curious about it.

According to following metadata, the logo of OM is at [`http://www.wurvoc.org/images/vocabularies/om-logo.jpg`](http://www.wurvoc.org/images/vocabularies/om-logo.jpg).

https://github.com/HajoRijgersberg/OM/blob/800447ad7575dbca303d62fdaad722e62a54f56d/om-2.0.rdf#L53

But currently (2020-09-08), this page returns 404 and we cannot access the logo image.
There are two kinds of image on the web archive[[1]](https://web.archive.org/web/20170715103751/http://www.wurvoc.org/images/vocabularies/om-logo.jpg)[[2]](https://web.archive.org/web/20160606174439/http://www.wurvoc.org/images/vocabularies/om-logo.jpg).
Which one is the logo of OM? Or neither?

If you would like, could you please host logo image at accessible place (e.g. this GitHub repository) or embed it to README and so on?

**Comment by HajoRijgersberg** [comment]
Hi B,
Thanks for your message, no not trivial at all! :)
The second image on the web archive is the correct one.
I have just uploaded it to this repository! https://github.com/HajoRijgersberg/OM/blob/master/om-logo.png
Best, Hajo

**Comment by cmplstofB** [comment]
Thank you very much!
