### ISSUE TITLE
Possible typo in IRI of "foot (international)"

### ISSUE THREAD

**Issue by andrea-perego** [HajoRijgersberg/OM#45]
The last component of the IRI includes an uppercase "I" (`foot-International`) which was instead lowercase in OM 1.8 (`foot-international`).

- OM 2 IRI: [`http://www.ontology-of-units-of-measure.org/resource/om-2/foot-International`](http://www.ontology-of-units-of-measure.org/resource/om-2/foot-International)
- OM 1.8 IRI: [`http://www.wurvoc.org/vocabularies/om-1.8/foot-international`](http://www.wurvoc.org/vocabularies/om-1.8/foot-international)

Is this intentional?

**Comment by HajoRijgersberg** [comment]
Hi Andrea,
Thanks for your attention! :)
The switch from lowercase to uppercase was due to the switch to CamelCase, when we moved from OM 1.8 to 2.0.
Cheers, Hajo

**Comment by andrea-perego** [comment]
Thanks a lot, @HajoRijgersberg .

I raised this issue as it leads to backward incompatibility problems, when moving from the use of OM 1.8 to OM 2 by simply replacing the URI prefix. But as this is a design choice and affects also other entries, it needs to be addressed differently at the data level.

**Comment by HajoRijgersberg** [comment]
Correct, Andrea. That's why we moved to a new main number at the time, i.e. 2, rather than 1.9.
Thanks again! :)
