### ISSUE TITLE
OM importing bibo?

### ISSUE THREAD

**Issue by GeorgJung** [HajoRijgersberg/OM#56]
Hi Hajo,

why does OM include concepts from http://purl.org/ontology/bibo/? Is there a rationale or could those (and the associated individuals) be removed?

Cheers,
Georg

**Comment by HajoRijgersberg** [comment]
Hey Georg,

Thanx for your question! :)
The answer: there are astronomy quantities and units with bibo references in OM.

Cheers, Hajo

**Comment by GeorgJung** [comment]
:-D

Okay, fair enough.

At first glance bibo looks quite out of place. I suppose some quantities and units are under debate and therefore need to name a reference? This is something that I would not have expected, but I see the point.

Probably even "meter" would need a reference, seeing that the definition has changed multiple times...

Closing this issue. Thanks!

**Comment by HajoRijgersberg** [comment]
I fully agree, I always see these classes listed in some platforms (automatically) along with the quantity- and unit-related classes. I wish we could do something about that. I'm not sure - perhaps it is not needed to include these bibo classes in OM, only relate to them. If someone knew more about this, that would be appreciated.

Indeed, in general quantities and particularly units have a history, definition, etc. Worthwhile to describe in documents and refer to.

Thanx! :)
