### ISSUE TITLE
typo on Fig.2 diagram

### ISSUE THREAD

**Issue by ashkotin** [HajoRijgersberg/OM#73]
It seems that the arrow for property om:hasNumericalValue on Fig.2 in https://github.com/HajoRijgersberg/OM should be inversed.

**Comment by HajoRijgersberg** [comment]
Thanx! You're right. I have indicated it for the time being in the caption of the figure now. In the near future I hope to find time to actually process it in the figure.

**Comment by HajoRijgersberg** [comment]
I have recently updated the figure.

**Comment by HajoRijgersberg** [comment]
I have recently updated the figure.

**Comment by ashkotin** [comment]
Direction of the arrow is the same on Fig.2.
https://github.com/HajoRijgersberg/OM/blob/master/images/OMAppleExample.png
