### ISSUE TITLE
Implement content negotiation for Ontology

### ISSUE THREAD

**Issue by nicholascar** [HajoRijgersberg/OM#8]
I can see that for an OM-defined concept such as Area (<http://www.ontology-of-units-of-measure.org/page/om-2/Area>) I can get the concept definition in RDF (in turtle: http://www.ontology-of-units-of-measure.org/data/om-2/Area.ttl) but I can't easily do this via content negotiation. This means I can't machine interact with the ontology as I hope to in Linked Data scenarios.

**Comment by dr-shorthair** [comment]
Duplicate of #5?

**Comment by nicholascar** [comment]
Ooops, duplicate
