### ISSUE TITLE
Cannot parse om-2.0.rdf anymore

### ISSUE THREAD

**Issue by mi-les** [HajoRijgersberg/OM#81]
Hi,

after the recent changes, I cannot parse the om-2.0.rdf file using `rdflib` anymore, like so:

```python
from rdflib import Graph

ontology_url = ("https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf")
g = Graph()
g.parse(ontology_url, format="xml")
```

This throws the following error:

```
rdflib.exceptions.ParserError: https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf:42642:2: Invalid property attribute URI: http://www.w3.org/1999/02/22-rdf-syntax-ns#resource
```

It worked just fine before the weekend. Anything gone wrong in the recent merges?

**Comment by HajoRijgersberg** [comment]
Hi Michaela,
Thanx for the notice. I'll look into it immediately.
Best, Hajo

**Comment by HajoRijgersberg** [comment]
I think I've found it: your error message gives a line number, 42642, that points to the first (of three) changes of authorLists of literature sources:

42641	<bibo:authorList rdf:parseType="Collection">
42642		<rdf:Description rdf:resource="&ombibo;Edwin_Budding"/>
42643		<rdf:Description rdf:resource="&ombibo;Osman_Demircan"/>
42644	</bibo:authorList>

In the past I did not have any rdf:Description in OM, so I think for some reason something goes wrong there. For now I'll comment such lines out. I'll give you a sign when I have done that (I'll do that immediately). Subsequently I will look for a more sustainable solution. I will keep you updated about that.

**Comment by HajoRijgersberg** [comment]
I have commented the lines out and uploaded a new version of om-2.0.rdf. Can you check if this one is parsing correctly? Thanx in advance.
Sorry for any inconvenience!

**Comment by mi-les** [comment]
Yep, that was it, works now! Thanks for the super quick response.

**Comment by HajoRijgersberg** [comment]
Thanx for your testing and quick response too! Hope to get back to this soon with an altered definition of the literature sources.

**Comment by jmkeil** [comment]
#82 fixes this. Sorry, I uses the wrong attribute. I just checked with Protege, which didn't complain about that.

**Comment by HajoRijgersberg** [comment]
No problem Jan Martin, thanx for your (quick) help! :)  So do I understand correctly that the use of rdf:Description was not the problem, but the use of rdf:resource after that rather than rdf:about?
Anyway, I have merged your pull request, and Michaela if you could try parsing this new version of OM again, that would be great! :) Thanx in advance!

**Comment by HajoRijgersberg** [comment]
I also often use Protégé for testing. ;)

**Comment by mi-les** [comment]
it's working :) thanks again!

**Comment by HajoRijgersberg** [comment]
Great! Thanx! :)
