### ISSUE TITLE
Unit request: m/min

### ISSUE THREAD

**Issue by echtbrecht** [HajoRijgersberg/OM#93]
Hi,

I would like to request a new UnitOfMeasure: metre per minute, centimetre per minute & millimetre per minute. There are already multiple units of measure describing speed (MetrePerSecond), but in machineering often velocities are described as a distance in function of a minute.

For example:
@prefix om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

om:MetrePerMinute rdf:type om:UnitOfMeasure ;
    rdfs:label "metre per minute"@en ;
    rdfs:label "meter per minuut"@nl ;
    rdfs:comment "Metre per minute is a unit of speed defined as metre divided by a minute."@en ;
    om:symbol "m/min"^^xsd:string ;
    om:alternativeSymbol "m min-1"^^xsd:string ;
    om:conversionFactorToReferenceUnit "0.016666666666666666"^^xsd:decimal ;
    om:hasDimensionVector om:ISQ-Dimension-Length-Time-1 ;
    om:hasReferenceUnit om:MetrePerSecond .

**Comment by HajoRijgersberg** [comment]
Hi, thanx, good suggestions! I'll add them end this week, would that be sufficient?
As to the conversion factor, that should be determined dynamically from the mathematical UnitDivision relation between the two units (e.g., metre and minute) and their hasFactor and hasUnit properties. As a side remark: I have plans to define these for all units in OM (so they don't have to be determined dynamically by the user), but this is not yet the case.

**Comment by echtbrecht** [comment]
Hi, 
I didn't expect a response back so quickly! By the end of the week is plenty in advance, thanks a lot! We are probably going to use this ontology within a context of machineering & welding combined with automation (PLC, motion controllers, robots). We got a lot of strange units available: some of them are brought to life because of rounding factors. For example: store a distance as decameter because it gives the right amount of precision within the available datatype. Having an ontology like this one available speeds up our development.

> As a side remark: I have plans to define these for all units in OM (so they don't have to be determined dynamically by the user), but this is not yet the 

I didn't understand this side remark to the fullest. Does this mean that there will be a unit available for every combination? For example: nanometer/nanosecond, millimeter/hour, millimeter/minute, and so on?

**Comment by HajoRijgersberg** [comment]
Sorry, I'm a bit later; some things came in between. But today will work! :)

**Comment by HajoRijgersberg** [comment]
Just added them! :)

**Comment by echtbrecht** [comment]
I've checked them, tested them out & they work perfectly. Thanks a lot!

**Comment by HajoRijgersberg** [comment]
Thanx for trying and your message! :)
Cheers, Hajo
